version: '3'

services:
  pdf-processor:
    build: .
    container_name: pdf-processor
    restart: unless-stopped
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 